### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by avengerx** [speed47/spectre-meltdown-checker#354] opened 2020-05-20 14:01 UTC
I am not sure how feasible that would be, but it would be indeed very useful if it was possible to run this tool on cygwin. I see this project is further up-to-date than other Windows apps like "InSpectre", for instance, so it would be a nice-to-have, cygwin support. :)

**Comment by speed47** [comment] 2020-05-31 11:08
Developing such a tool from Windows has to be made completely from scratch, and Cygwin (or WSL/WSL2) can't help here, as we're digging very deep in the operating system and on the hardware. No compatibility layer can help unfortunately! :(
(Duplicate of #289 )

**Closed by speed47** 2020-05-31 11:08 UTC
